_login:
  pattern:  /
  defaults: { _controller: ChatterBoxBundle:Login:index }

_readrss:
  pattern: /readrss
  defaults: {_controller: ChatterBoxBundle:ReadRss:index }

_readrss_create:
  pattern: /readrss/create
  defaults: {_controller: ChatterBoxBundle:ReadRss:createRss }

_readrss_delete:
  pattern: /readrss/delete
  defaults: {_controller: ChatterBoxBundle:ReadRss:deleteRss }

_dashboard:
  pattern: /dashboard
  defaults: {_controller: ChatterBoxBundle:Dashboard:index}